name: Tyler Hawes
favicon: null
layout_spectrum: 0.14587316336110234
typography_spectrum: 0.8814438239205629
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.38906252244487405
  lightness: 0.8743125924374908
  saturation: 0.7016911753453314
  rhythmicContrast: 0.7233827516902238
purpose: []
